name: Log into GHCR, Setup Docker Buildx, Cache Docker layers
description: a composite action used to simplify docker_publish.yml. It logs into GHCR, sets up Buildx, and caches Docker layers 
inputs:
  token:
    description: 'secrets.GITHUB_TOKEN used to log into GHCR'
    required: true
runs:
  using: "composite"
  steps:
   - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.token }}
        
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
      with:
        install: true

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache-${{ github.sha }}
        # Key is named differently to avoid collision
        key: ${{ runner.os }}-multi-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-multi-buildx
          