name: setup QEMU & log into GHCR
description: a composite action to simplify docker_publish.yml. It sets up QEMU and logs into GHCR
inputs:
  token:
    description: 'secrets.GITHUB_TOKEN used to log into GHCR'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.token }}
